apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "policy-server.fullname" . }}-sync
  labels:
    {{- include "policy-server.labels" . | nindent 4 }}
data:
  dambi-sync.toml: |-
    {{- .Values.syncConfig | nindent 4 }}
