apiVersion: v1
kind: Service
metadata:
  name: {{ include "policy-server.fullname" . }}-api
  labels:
    {{- include "policy-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    {{- include "policy-server.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
