// AUTO-GENERATED from func_module/field-explorer.html — DO NOT EDIT BY HAND.
// Curated Korean label + one-line desc for every schema field path, used by
// the form picker (cedar/form/field-catalog.ts) as the label/desc source of
// truth. Regenerate via the field-explorer curation pipeline.

export interface CuratedFieldMeta {
  /** Korean display label shown in the form's field picker. */
  label: string;
  /** One-line plain-language hint shown under the label. */
  desc: string;
}

export const CURATED_FIELD_META: Record<string, CuratedFieldMeta> = {
  "context.aTokenPriceUsd": { label: "aToken 기초자산 가격 (USD)", desc: "aToken 기초자산의 가격 (USD, Aave)" },
  "context.account": { label: "쿨다운 대상 계정의 주소", desc: "스테이크가 쿨다운에 들어가는 계정 (Aave)" },
  "context.actualAmount": { label: "실제 청구량 (원본)", desc: "실제로 받을 토큰 양 (원본 형식)" },
  "context.actualAmountNano": { label: "실제 청구량 (비교용)", desc: "실제로 받을 토큰 양 (크기 비교용)" },
  "context.actualAmountUsd": { label: "실제 청구량 (USD)", desc: "실제로 받을 토큰의 달러 가치" },
  "context.adapter": { label: "어댑터 컨트랙트의 주소", desc: "프로토콜에 연결하는 어댑터의 주소 (Aave V3)" },
  "context.addCollateralAmount": { label: "추가 담보 수량 (원본)", desc: "더 맡기는 담보 토큰 양 (원본)" },
  "context.addCollateralAmountNano": { label: "추가 담보 수량 (비교용)", desc: "크기 비교에 쓰는 추가 담보 수량" },
  "context.addCollateralToken.key.address": { label: "추가 담보 토큰의 주소", desc: "추가로 맡길 토큰 컨트랙트의 주소" },
  "context.addCollateralToken.key.chain": { label: "추가 담보 토큰의 네트워크", desc: "추가 담보 토큰이 있는 네트워크" },
  "context.addCollateralToken.key.hlToken": { label: "추가 담보 토큰 식별자 (하이퍼리퀴드)", desc: "추가로 맡기는 담보 토큰의 하이퍼리퀴드 식별자" },
  "context.affectedPositions": { label: "영향받는 포지션 목록", desc: "이 변경이 미치는 포지션 ID 목록" },
  "context.allocatedAmount": { label: "배정 수량 (원본)", desc: "배정받는 토큰 양 (원본 형식)" },
  "context.allocatedAmountNano": { label: "배정 수량 (비교용)", desc: "배정받는 토큰 양 (크기 비교용)" },
  "context.allocatedAmountUsd": { label: "배정 수량 (USD)", desc: "배정받는 토큰의 달러 가치" },
  "context.allocatedToken.key.address": { label: "배정 토큰의 주소", desc: "배정받는 토큰의 컨트랙트 주소" },
  "context.allocatedToken.key.chain": { label: "배정 토큰의 네트워크", desc: "배정 토큰이 있는 네트워크" },
  "context.allocatedToken.key.hlToken": { label: "배정 토큰 식별자 (하이퍼리퀴드)", desc: "배정 토큰의 하이퍼리퀴드 식별자" },
  "context.allocationDelay": { label: "할당 지연", desc: "오퍼레이터 할당·슬래싱 지연 (블록 수)" },
  "context.amount": { label: "수량 (원본)", desc: "토큰 단위 그대로의 수량(16진수)" },
  "context.amountNano": { label: "수량 (비교용)", desc: "크기 비교(≥, ≤)에 쓰는 수량" },
  "context.amountUsd": { label: "수량 (USD 환산)", desc: "이번 거래의 달러 환산 가치" },
  "context.amounts": { label: "요청 수량 목록", desc: "출금 요청별 수량 목록 (Lido)" },
  "context.approved": { label: "승인 여부", desc: "NFT 컬렉션 전체를 승인하는지" },
  "context.approverSalt": { label: "승인용 솔트", desc: "서명 충돌 방지용 난수 (EIP-712)" },
  "context.asset.key.address": { label: "자산 토큰의 주소", desc: "GHO와 맞바꾸는 자산 토큰의 주소 (Aave)" },
  "context.asset.key.chain": { label: "자산이 있는 네트워크", desc: "자산 토큰이 올라간 네트워크" },
  "context.asset.key.hlToken": { label: "자산 식별자 (하이퍼리퀴드)", desc: "자산 토큰의 하이퍼리퀴드 식별자" },
  "context.assetIn.key.address": { label: "입력 자산의 주소", desc: "넣는 자산 토큰의 주소" },
  "context.assetIn.key.chain": { label: "입력 자산의 네트워크", desc: "넣는 자산이 있는 네트워크" },
  "context.assetIn.key.hlToken": { label: "입력 자산 식별자 (하이퍼리퀴드)", desc: "넣는 자산의 하이퍼리퀴드 식별자" },
  "context.assetOut.key.address": { label: "출력 자산의 주소", desc: "받는 자산 토큰의 주소" },
  "context.assetOut.key.chain": { label: "출력 자산의 네트워크", desc: "받는 자산이 있는 네트워크" },
  "context.assetOut.key.hlToken": { label: "출력 자산 식별자 (하이퍼리퀴드)", desc: "받는 자산의 하이퍼리퀴드 식별자" },
  "context.assetPriceUsd": { label: "자산 가격 (USD)", desc: "대상 자산의 가격 (USD)" },
  "context.authorized": { label: "권한 받는 주소", desc: "권한을 부여받는 대상의 주소" },
  "context.authorizer": { label: "권한 주는 주소", desc: "권한을 부여하는 주체의 주소" },
  "context.availableLiquidity": { label: "사용 가능 유동성", desc: "빌릴 수 있는 유동성 (원본)" },
  "context.availableOi": { label: "사용 가능 미결제약정", desc: "더 늘릴 수 있는 미결제약정 (원본)" },
  "context.availableToWithdraw": { label: "출금 가능 금액", desc: "지금 뺄 수 있는 금액 (원본)" },
  "context.baseAmount": { label: "기준 수량 (원본)", desc: "기준 자산의 수량 (원본)" },
  "context.baseAmountNano": { label: "기준 수량 (비교용)", desc: "크기 비교에 쓰는 기준 자산의 수량" },
  "context.baseAsset.key.address": { label: "기준 자산의 주소", desc: "기준 자산 토큰의 주소" },
  "context.baseAsset.key.chain": { label: "기준 자산의 네트워크", desc: "기준 자산이 있는 네트워크" },
  "context.baseAsset.key.hlToken": { label: "기준 자산 식별자 (하이퍼리퀴드)", desc: "기준 자산의 하이퍼리퀴드 식별자" },
  "context.bestAsk": { label: "최우선 매도호가", desc: "주문 시점 호가창의 최저 매도가" },
  "context.bestBid": { label: "최우선 매수호가", desc: "주문 시점 호가창의 최고 매수가" },
  "context.buy.key.address": { label: "살 토큰의 주소", desc: "매수할 토큰 컨트랙트의 주소" },
  "context.buy.key.chain": { label: "살 토큰이 있는 네트워크", desc: "매수할 토큰이 올라간 네트워크" },
  "context.buy.key.hlToken": { label: "살 토큰 식별자 (하이퍼리퀴드)", desc: "사는 토큰의 하이퍼리퀴드 식별자" },
  "context.buyMin": { label: "최소 매수량 (원본)", desc: "최소한 사야 하는 토큰의 양" },
  "context.buyMinNano": { label: "최소 매수량 (비교용)", desc: "크기 비교에 쓰는 최소 매수량" },
  "context.buyMinUsd": { label: "최소 매수량 (USD)", desc: "최소 매수량의 달러 환산값" },
  "context.calldata": { label: "실행 데이터 (calldata)", desc: "어댑터에 보내는 호출 데이터 (16진수)" },
  "context.categoryConfig.assetsInCategory": { label: "카테고리 자산 목록", desc: "카테고리에 속한 자산의 목록 (Aave e-Mode)" },
  "context.categoryConfig.categoryCode": { label: "카테고리 코드", desc: "카테고리의 코드 번호 (Aave e-Mode)" },
  "context.categoryConfig.liquidationBonusBp": { label: "카테고리 청산 보너스 (bp)", desc: "카테고리의 청산 할인폭 (100bp=1%)" },
  "context.categoryConfig.liquidationThresholdBp": { label: "카테고리 청산 기준선 (bp)", desc: "카테고리의 청산 기준 비율 (100bp=1%)" },
  "context.categoryConfig.ltvBp": { label: "카테고리 담보인정비율 (bp)", desc: "카테고리의 담보인정비율 (100bp=1%)" },
  "context.categoryConfig.priceSource": { label: "카테고리 가격 출처의 주소", desc: "카테고리 가격 소스 컨트랙트의 주소 (Aave e-Mode)" },
  "context.categoryId": { label: "카테고리 번호", desc: "선택한 카테고리의 번호 (Aave e-Mode)" },
  "context.chain": { label: "네트워크", desc: "거래가 일어나는 네트워크" },
  "context.childCount": { label: "묶음 거래 개수", desc: "묶음에 담긴 자식 거래의 개수" },
  "context.children": { label: "묶음 거래 목록", desc: "한 번에 실행할 자식 거래들의 목록" },
  "context.claimTarget.chain": { label: "배포 컨트랙트가 있는 네트워크", desc: "에어드랍을 청구하는 네트워크" },
  "context.claimTarget.contract": { label: "배포 컨트랙트의 주소", desc: "에어드랍을 청구하는 컨트랙트의 주소" },
  "context.claimTarget.index": { label: "머클 잎 번호", desc: "머클 트리에서 받는 사람의 잎 위치" },
  "context.claimTarget.kind": { label: "청구 방식 종류", desc: "머클·서명·스테이킹 중 청구 방식" },
  "context.claimToken.key.address": { label: "청구 토큰의 주소", desc: "받게 될 토큰 컨트랙트의 주소" },
  "context.claimToken.key.chain": { label: "청구 토큰이 있는 네트워크", desc: "받게 될 토큰이 있는 네트워크" },
  "context.claimToken.key.hlToken": { label: "청구 토큰 식별자 (하이퍼리퀴드)", desc: "받게 될 토큰의 하이퍼리퀴드 식별자" },
  "context.claimWindowEnd": { label: "청구 마감 시각", desc: "청구 기간이 끝나는 시각 (유닉스 초)" },
  "context.claimWindowStart": { label: "청구 시작 시각", desc: "청구 기간이 시작되는 시각 (유닉스 초)" },
  "context.claimable": { label: "청구 가능 목록", desc: "받을 수 있는 펀딩비 자산 목록" },
  "context.claimableNow": { label: "지금 청구 가능액", desc: "지금 받을 수 있는 토큰 양" },
  "context.collatAsset.key.address": { label: "담보 자산의 주소", desc: "압류할 담보 자산의 주소" },
  "context.collatAsset.key.chain": { label: "담보 자산의 네트워크", desc: "담보 자산이 있는 네트워크" },
  "context.collatAsset.key.hlToken": { label: "담보 자산 식별자 (하이퍼리퀴드)", desc: "담보 자산의 하이퍼리퀴드 식별자" },
  "context.collatAssetPrice": { label: "담보 자산의 가격 (USD)", desc: "담보 자산의 가격 (USD)" },
  "context.collateralAmount": { label: "담보 수량 (원본)", desc: "맡기는 담보 토큰 양 (원본)" },
  "context.collateralAmountNano": { label: "담보 수량 (비교용)", desc: "크기 비교에 쓰는 담보 수량" },
  "context.collateralAmountUsd": { label: "담보 수량 (USD)", desc: "담보의 달러 환산 수량" },
  "context.collateralAsset.key.address": { label: "담보 자산의 주소", desc: "담보 자산 토큰의 주소" },
  "context.collateralAsset.key.chain": { label: "담보 자산의 네트워크", desc: "담보 자산이 있는 네트워크" },
  "context.collateralAsset.key.hlToken": { label: "담보 자산 식별자 (하이퍼리퀴드)", desc: "담보 자산의 하이퍼리퀴드 식별자" },
  "context.collateralToken.key.address": { label: "담보 토큰의 주소", desc: "담보 토큰 컨트랙트의 주소" },
  "context.collateralToken.key.chain": { label: "담보 토큰의 네트워크", desc: "담보 토큰이 있는 네트워크" },
  "context.collateralToken.key.hlToken": { label: "담보 토큰 식별자 (하이퍼리퀴드)", desc: "담보 토큰의 하이퍼리퀴드 식별자" },
  "context.competingOrders": { label: "경쟁 주문 수", desc: "같은 거래쌍의 경쟁 주문 개수" },
  "context.conduitKey": { label: "컨듀잇 키", desc: "전송을 거치는 컨듀잇 (Seaport)" },
  "context.consideration": { label: "받을 항목 목록", desc: "판매자가 받는 대금·수수료·로열티" },
  "context.contract": { label: "컨트랙트의 주소", desc: "거래 상대 컨트랙트의 주소" },
  "context.counter": { label: "주문 카운터", desc: "작성자의 주문 논스 (Seaport)" },
  "context.currentBorrowRate": { label: "현재 차입 금리", desc: "현재 차입 연이율" },
  "context.currentDebt": { label: "현재 빚", desc: "현재 총 빚 (원본)" },
  "context.currentDebtStable": { label: "현재 고정금리 빚", desc: "현재 고정금리 빚 (원본, Aave)" },
  "context.currentDebtVariable": { label: "현재 변동금리 빚", desc: "현재 변동금리 빚 (원본, Aave)" },
  "context.currentDelegate": { label: "현재 위임받은 대상", desc: "현재 권한을 위임받은 대상의 주소" },
  "context.currentPrice": { label: "현재 가격", desc: "풀의 현재 가격 (범위 검증용)" },
  "context.custom.alreadyGranted": { label: "이미 승인된 권한", desc: "이 지출 권한이 이미 부여돼 있는지" },
  "context.custom.approvalAmountOverBalance": { label: "승인액의 잔액 초과분", desc: "승인 금액이 내 잔액을 넘는 정도" },
  "context.custom.approvalIsUnlimited": { label: "무제한 승인 여부", desc: "지출 권한을 무제한으로 주는지" },
  "context.custom.bidApprovalIsUnlimited": { label: "입찰 승인 무제한 여부", desc: "입찰용 지출 권한이 무제한인지" },
  "context.custom.bidApprovalOverBalance": { label: "입찰 승인액의 잔액 초과분", desc: "입찰 승인 금액이 내 잔액을 넘는 정도" },
  "context.custom.chainMismatch": { label: "네트워크 불일치", desc: "서명의 네트워크가 지금과 다른지" },
  "context.custom.crossesZero": { label: "방향 전환 여부", desc: "이 거래로 포지션이 반대로 넘어가는지" },
  "context.custom.gasCostRatioOfValue": { label: "가스비 비중", desc: "가스비가 거래액에서 차지하는 비율" },
  "context.custom.gasCostUsd": { label: "예상 가스비 (USD)", desc: "예상 가스비의 달러 환산값" },
  "context.custom.inputAmountNano": { label: "입력 수량 (비교용)", desc: "정책 저장 시 채워지는 크기 비교용 입력 수량" },
  "context.custom.inputUsd": { label: "입력액 (USD)", desc: "정책 저장 시 채워지는 입력액의 달러 환산값" },
  "context.custom.leverageIncrease": { label: "레버리지 증가 여부", desc: "이 거래로 배율이 올라가는지" },
  "context.custom.orderLeverage": { label: "주문 레버리지", desc: "이 주문의 배율" },
  "context.custom.pctOfHolding": { label: "보유량 대비 전송 비율", desc: "내 보유량 중 내보내는 비율" },
  "context.custom.permitAllowanceUsd": { label: "서명 승인 한도 (USD)", desc: "서명이 허용하는 지출 한도의 달러 환산" },
  "context.custom.permitExpiryHorizonSec": { label: "서명 만료까지 시간 (초)", desc: "서명이 만료되기까지 남은 시간 (초)" },
  "context.custom.permitTokenIsHeld": { label: "보유 토큰 대상 여부", desc: "이미 가진 토큰을 노린 청구인지 (드레이너 신호)" },
  "context.custom.resultingAllowanceOverBalance": { label: "최종 승인액의 잔액 초과분", desc: "승인 후 총 한도가 잔액을 넘는 정도" },
  "context.custom.resultingAllowanceUnlimited": { label: "최종 승인 무제한 여부", desc: "승인 후 총 한도가 무제한이 되는지" },
  "context.deadline": { label: "마감 시각", desc: "서명이 만료되는 시각, 유닉스 초 (ERC20 Permit)" },
  "context.debtAsset.key.address": { label: "빌린 자산의 주소", desc: "갚아줄 빚 자산의 주소" },
  "context.debtAsset.key.chain": { label: "빌린 자산의 네트워크", desc: "빚 자산이 있는 네트워크" },
  "context.debtAsset.key.hlToken": { label: "빌린 자산 식별자 (하이퍼리퀴드)", desc: "빌린 자산의 하이퍼리퀴드 식별자" },
  "context.debtAssetPrice": { label: "빌린 자산의 가격 (USD)", desc: "빚 자산의 가격 (USD)" },
  "context.debtToCover": { label: "갚을 빚 (원본)", desc: "청산에서 갚는 빚의 수량 (원본)" },
  "context.debtToCoverNano": { label: "갚을 빚 (비교용)", desc: "크기 비교에 쓰는 갚을 빚 수량" },
  "context.debtToCoverUsd": { label: "갚을 빚 (USD)", desc: "청산에서 갚는 빚의 금액 (USD)" },
  "context.delegatee": { label: "위임받는 주소", desc: "차입 권한을 위임받는 주소 (Aave 신용위임)" },
  "context.delegationApprover": { label: "위임 승인자의 주소", desc: "위임을 함께 서명할 주소 (EigenLayer)" },
  "context.delegationKind": { label: "위임 종류", desc: "위임할 권한의 종류 (전체/투표/제안)" },
  "context.delta": { label: "증거금 변화량", desc: "증거금 변화량 (양수 입금, 음수 출금)" },
  "context.denomination": { label: "수량 기준", desc: "수량을 지분으로 셀지 자산으로 셀지" },
  "context.depositShares": { label: "예치 지분 목록", desc: "전략별 출금 지분 (내부 지분 단위)" },
  "context.destination": { label: "받는 사람의 주소", desc: "자산을 받는 주소 (하이퍼리퀴드)" },
  "context.destinationDex": { label: "도착 DEX 이름", desc: "자산이 도착하는 DEX의 이름 (하이퍼리퀴드)" },
  "context.direction.amountIn": { label: "입력 수량 (원본)", desc: "입력 토큰의 정확한 양 (원본 형식)" },
  "context.direction.amountInNano": { label: "입력 수량 (비교용)", desc: "크기 비교에 쓰는 입력 수량" },
  "context.direction.amountInUsd": { label: "입력 수량 (USD)", desc: "입력 토큰량의 달러 환산값" },
  "context.direction.amountOut": { label: "출력 수량 (원본)", desc: "출력 토큰의 정확한 양 (원본 형식)" },
  "context.direction.amountOutNano": { label: "출력 수량 (비교용)", desc: "크기 비교에 쓰는 출력 수량" },
  "context.direction.amountOutUsd": { label: "출력 수량 (USD)", desc: "출력 토큰량의 달러 환산값" },
  "context.direction.kind": { label: "스왑 방향", desc: "입력 고정인지 출력 고정인지 (Uniswap)" },
  "context.direction.maxAmountIn": { label: "최대 입력 수량 (원본)", desc: "최대로 쓸 수 있는 입력 토큰의 양" },
  "context.direction.maxAmountInNano": { label: "최대 입력 수량 (비교용)", desc: "크기 비교에 쓰는 최대 입력 수량" },
  "context.direction.minAmountOut": { label: "최소 출력 수량 (원본)", desc: "최소한 받아야 하는 출력 토큰의 양" },
  "context.direction.minAmountOutNano": { label: "최소 출력 수량 (비교용)", desc: "크기 비교에 쓰는 최소 출력 수량" },
  "context.eligibleAsCollat": { label: "담보 가능 여부", desc: "담보로 쓸 수 있는 자산인지 여부" },
  "context.embedded_permit.deadline": { label: "동봉 서명의 마감 시각", desc: "서명의 만료 시각, 유닉스 초 (EIP-2612)" },
  "context.embedded_permit.value": { label: "동봉 서명의 허용 금액", desc: "출금 큐에 허용한 금액 (EIP-2612)" },
  "context.endTime": { label: "종료 시각", desc: "주문이 만료되는 시각" },
  "context.expectedAmountOut": { label: "예상 출력량", desc: "실행 전 견적된 출력 토큰의 양" },
  "context.expectedFillPrice": { label: "예상 체결가", desc: "의도 주문의 예상 체결 가격" },
  "context.expectedSteth": { label: "예상 stETH 수령량", desc: "unwrap으로 받을 stETH의 양 (Lido)" },
  "context.expectedTokenPrice": { label: "예상 토큰 가격", desc: "판매 토큰의 예상 가격" },
  "context.expectedWsteth": { label: "예상 wstETH 수령량", desc: "wrap으로 받을 wstETH의 양 (Lido)" },
  "context.expiresAt": { label: "만료 시각", desc: "승인이 만료되는 시각, 유닉스 초 (Permit2)" },
  "context.feeBp": { label: "수수료 (bp)", desc: "적용 수수료율 (100bp=1%)" },
  "context.feeMakerBp": { label: "메이커 수수료 (bp)", desc: "메이커 수수료율 (100bp=1%)" },
  "context.feeTakerBp": { label: "테이커 수수료 (bp)", desc: "테이커 수수료율 (100bp=1%)" },
  "context.feesOwed": { label: "미지급 수수료 목록", desc: "포지션에 쌓인 미수령 수수료 (Uniswap V3)" },
  "context.freeMarginAfter": { label: "조정 후 여유 증거금", desc: "조정 뒤 남는 여유 증거금 (원본)" },
  "context.from": { label: "보내는 사람의 주소", desc: "지분을 보내는 사람의 주소 (Lido)" },
  "context.fulfillerConduitKey": { label: "이행자의 컨듀잇 키", desc: "구매자가 쓰는 컨듀잇 (Seaport)" },
  "context.fundingAccrued": { label: "누적 펀딩비", desc: "그동안 쌓인 펀딩비 (+/-)" },
  "context.fundingRate": { label: "펀딩 요율", desc: "현재 펀딩 요율 (소수)" },
  "context.gasEstimate": { label: "예상 가스량 (원본)", desc: "거래에 들 것으로 본 가스의 양" },
  "context.gauge": { label: "투표할 게이지의 주소", desc: "투표 가중치를 배분할 게이지 (Curve)" },
  "context.gauges": { label: "게이지 주소 목록", desc: "보상을 청구할 게이지 주소들" },
  "context.gho.key.address": { label: "GHO 토큰의 주소", desc: "GHO 스테이블코인 토큰의 주소 (Aave)" },
  "context.gho.key.chain": { label: "GHO 토큰이 있는 네트워크", desc: "GHO 토큰이 올라간 네트워크" },
  "context.gho.key.hlToken": { label: "GHO 토큰 식별자 (하이퍼리퀴드)", desc: "GHO 토큰의 하이퍼리퀴드 식별자" },
  "context.governancePower": { label: "보유 투표권", desc: "현재 보유한 거버넌스 투표권" },
  "context.initialMarginBp": { label: "초기 증거금률 (bp)", desc: "진입에 필요한 증거금률 (100bp=1%)" },
  "context.isAuthorized": { label: "권한 부여 여부", desc: "권한을 켜는지 끄는지 (Aave)" },
  "context.isBatch": { label: "묶음 거래 여부", desc: "여러 주문을 한 번에 이행하는지" },
  "context.isClaimable": { label: "청구 가능 여부", desc: "지금 받을 수 있는가" },
  "context.isStillClaimable": { label: "아직 청구 가능 여부", desc: "만료·중복 없이 아직 받을 수 있는지" },
  "context.isUndelegate": { label: "위임 해제 여부", desc: "참이면 위임 해제, 거짓이면 위임" },
  "context.kind": { label: "주변 작업의 종류", desc: "담보 교환 등 작업의 종류 (Aave V3)" },
  "context.leverage": { label: "유효 레버리지", desc: "이 주문에 실제 적용되는 배율" },
  "context.limitAmount": { label: "한도 수량 (원본)", desc: "허용하는 한도 수량 (원본)" },
  "context.limitAmountNano": { label: "한도 수량 (비교용)", desc: "크기 비교에 쓰는 한도 수량" },
  "context.liquidationBonus": { label: "청산 보너스", desc: "청산자가 받는 할인폭 (100bp=1%)" },
  "context.maintenanceBp": { label: "유지 증거금률 (bp)", desc: "포지션 유지에 필요한 증거금률 (100bp=1%)" },
  "context.marginMode": { label: "증거금 방식", desc: "증거금 방식 (교차/격리)" },
  "context.marginReallocation": { label: "증거금 재배분 목록", desc: "포지션별 증거금 재배분 양 목록" },
  "context.markPrice": { label: "마크 가격", desc: "청산을 판단하는 기준 가격" },
  "context.market.symbol": { label: "시장 심볼", desc: "선물 시장의 종목 심볼" },
  "context.market.venue.chain": { label: "프로토콜의 네트워크", desc: "선물 시장이 있는 네트워크" },
  "context.market.venue.name": { label: "프로토콜 이름", desc: "선물 시장의 프로토콜 이름 (하이퍼리퀴드는 \"hyperliquid\")" },
  "context.maxLeverage": { label: "최대 레버리지", desc: "이 시장에서 허용되는 최대 배율" },
  "context.minCollateralAmount": { label: "최소 담보 수량 (원본)", desc: "받아야 할 최소 담보의 수량 (원본)" },
  "context.minCollateralAmountNano": { label: "최소 담보 수량 (비교용)", desc: "크기 비교에 쓰는 최소 담보의 수량" },
  "context.newLeverage": { label: "변경 후 레버리지", desc: "변경 뒤 적용될 배율" },
  "context.newLiqPrices": { label: "변경 후 청산가 목록", desc: "변경 뒤 포지션별 청산가 목록" },
  "context.newMode": { label: "변경 후 증거금 방식", desc: "변경 뒤 증거금 방식 (교차/격리)" },
  "context.newOperator": { label: "새 오퍼레이터의 주소", desc: "새로 위임받을 오퍼레이터 (EigenLayer)" },
  "context.nextUnlockAmount": { label: "다음 잠금해제 수량", desc: "다음에 풀리는 토큰 양" },
  "context.nextUnlockTime": { label: "다음 잠금해제 시각", desc: "다음 베스팅 해제 시각" },
  "context.nftKey.address": { label: "NFT 컨트랙트의 주소", desc: "NFT 컬렉션 컨트랙트의 주소" },
  "context.nftKey.chain": { label: "NFT의 네트워크", desc: "NFT가 있는 네트워크" },
  "context.nftKey.contract": { label: "NFT 컬렉션의 주소", desc: "NFT 컬렉션 컨트랙트의 주소" },
  "context.nftKey.hlToken": { label: "NFT 식별자 (하이퍼리퀴드)", desc: "NFT의 하이퍼리퀴드 식별자" },
  "context.nftKey.standard": { label: "NFT 규격 (ERC)", desc: "NFT 규격 (erc721/erc1155)" },
  "context.nftKey.tokenId": { label: "NFT의 번호", desc: "NFT 토큰의 번호 (16진수)" },
  "context.nonce": { label: "논스", desc: "서명 재사용을 막는 일회용 번호 (Permit2)" },
  "context.nonce.bit": { label: "논스 비트", desc: "논스 비트 위치, 0~255 (Permit2)" },
  "context.nonce.word": { label: "논스 워드", desc: "논스가 저장된 워드 (Permit2)" },
  "context.offer": { label: "내줄 항목 목록", desc: "판매자가 내주는 항목" },
  "context.offerer": { label: "주문 작성자의 주소", desc: "주문에 서명한 판매자" },
  "context.onBehalfOf": { label: "대리 실행 대상의 주소", desc: "누구를 대신해 실행하는지의 주소" },
  "context.openOrdersCount": { label: "미체결 주문 수", desc: "이 시장에 열려 있는 내 주문 수" },
  "context.operator": { label: "오퍼레이터의 주소", desc: "지분을 위임받을 오퍼레이터 (EigenLayer)" },
  "context.oraclePrice": { label: "오라클 가격", desc: "오라클이 알려주는 기준 가격" },
  "context.orderCount": { label: "주문 개수", desc: "한 번에 처리하는 주문 수" },
  "context.orderHash": { label: "주문 해시", desc: "의도 주문의 식별 해시값" },
  "context.orderId": { label: "주문 ID", desc: "주문의 고유 ID" },
  "context.orderKind": { label: "주문 종류", desc: "의도 주문의 유형 (limit·dutch·rfq)" },
  "context.orderNonce": { label: "주문 논스", desc: "정산에 사용한 주문의 논스값" },
  "context.orderType": { label: "주문 종류", desc: "주문의 공개·제한 방식 (Seaport)" },
  "context.orderType.durationMinutes": { label: "TWAP 분산 시간", desc: "TWAP 주문을 나눠 체결할 시간" },
  "context.orderType.kind": { label: "주문 유형", desc: "지정가·스탑·TWAP 중 무엇인지" },
  "context.orderType.limitPrice": { label: "스탑 지정가", desc: "스탑 지정가 주문에서 거는 지정 가격" },
  "context.orderType.orderKind": { label: "스탑 주문 종류", desc: "스탑/지정·익절 등 세부 종류" },
  "context.orderType.price": { label: "주문 지정가", desc: "지정가 주문에서 거는 가격" },
  "context.orderType.randomize": { label: "TWAP 무작위화 여부", desc: "TWAP 분할을 무작위로 나누는지" },
  "context.orderType.timeInForce.kind": { label: "주문 체결 정책", desc: "주문이 살아 있는 방식 (gtc/ioc 등)" },
  "context.orderType.timeInForce.until": { label: "주문 만료 시각", desc: "주문이 만료되는 시각 (유닉스 초)" },
  "context.orderType.triggerPrice": { label: "발동 가격", desc: "스탑 주문이 발동되는 가격" },
  "context.owner": { label: "소유자", desc: "토큰을 보유한 주소" },
  "context.params.amountDesired.a": { label: "희망 수량 A (원본)", desc: "공급 시 토큰A의 희망량" },
  "context.params.amountDesired.b": { label: "희망 수량 B (원본)", desc: "공급 시 토큰B의 희망량" },
  "context.params.amountMin.a": { label: "첫째 토큰 최소 수량", desc: "토큰A를 최소 이만큼 넣겠다는 하한 (원본 형식)" },
  "context.params.amountMin.b": { label: "둘째 토큰 최소 수량", desc: "토큰B를 최소 이만큼 넣겠다는 하한 (원본 형식)" },
  "context.params.amountsOut": { label: "출력 수량 목록", desc: "불균형 제거 시 토큰별 출력량 (Curve)" },
  "context.params.kind": { label: "작업 종류", desc: "유동성 작업의 종류 (pooled 등)" },
  "context.params.liquidityBurn": { label: "소각할 유동성 (원본)", desc: "줄일 포지션 유동성의 양 (Uniswap V3)" },
  "context.params.lpAmount": { label: "소각할 LP 수량 (원본)", desc: "태울 LP 토큰의 양" },
  "context.params.lpToken.key.address": { label: "LP 토큰의 주소", desc: "LP 토큰 컨트랙트의 주소" },
  "context.params.lpToken.key.chain": { label: "LP 토큰이 있는 네트워크", desc: "LP 토큰이 올라간 네트워크" },
  "context.params.lpToken.key.hlToken": { label: "LP 토큰 식별자 (하이퍼리퀴드)", desc: "LP 토큰의 하이퍼리퀴드 식별자" },
  "context.params.maxLpBurn": { label: "최대 소각 LP (원본)", desc: "불균형 제거 시 최대로 태울 LP의 양 (Curve)" },
  "context.params.minLpOut": { label: "최소 LP 수령량", desc: "공급 후 최소한 받아야 하는 LP 토큰의 양" },
  "context.params.minOut": { label: "최소 수령 목록", desc: "유동성 제거 시 토큰별 최소 수령량" },
  "context.params.minOutOne": { label: "최소 수령량 (단일)", desc: "단일 토큰 제거 시 최소 수령량 (Curve)" },
  "context.params.nftKey.address": { label: "NFT 컨트랙트의 주소", desc: "포지션 NFT 컨트랙트의 주소" },
  "context.params.nftKey.chain": { label: "NFT가 있는 네트워크", desc: "포지션 NFT가 올라간 네트워크" },
  "context.params.nftKey.contract": { label: "NFT 컨트랙트의 주소", desc: "포지션 NFT 컨트랙트의 주소" },
  "context.params.nftKey.hlToken": { label: "포지션 NFT 식별자 (하이퍼리퀴드)", desc: "포지션 NFT의 하이퍼리퀴드 식별자" },
  "context.params.nftKey.standard": { label: "NFT 규격", desc: "NFT의 토큰 규격 (erc721 등)" },
  "context.params.nftKey.tokenId": { label: "NFT의 번호", desc: "포지션 NFT의 토큰 번호" },
  "context.params.poolPair.tokenA.key.address": { label: "풀 토큰A의 주소", desc: "같이 예치하는 첫째 토큰의 주소" },
  "context.params.poolPair.tokenA.key.chain": { label: "풀 토큰A가 있는 네트워크", desc: "첫째 토큰이 올라간 네트워크" },
  "context.params.poolPair.tokenA.key.hlToken": { label: "풀 토큰A 식별자 (하이퍼리퀴드)", desc: "풀의 첫째 토큰의 하이퍼리퀴드 식별자" },
  "context.params.poolPair.tokenB.key.address": { label: "풀 토큰B의 주소", desc: "같이 예치하는 둘째 토큰의 주소" },
  "context.params.poolPair.tokenB.key.chain": { label: "풀 토큰B가 있는 네트워크", desc: "둘째 토큰이 올라간 네트워크" },
  "context.params.poolPair.tokenB.key.hlToken": { label: "풀 토큰B 식별자 (하이퍼리퀴드)", desc: "풀의 둘째 토큰의 하이퍼리퀴드 식별자" },
  "context.params.range.activeId": { label: "활성 Bin ID (Trader Joe LB)", desc: "현재 활성 Bin의 ID" },
  "context.params.range.kind": { label: "구간 종류", desc: "범위 지정 방식 (tick·bin·custom)" },
  "context.params.range.liquidity": { label: "구간 유동성 (원본)", desc: "해당 범위에 넣는 유동성의 양" },
  "context.params.range.protocol": { label: "구간 프로토콜", desc: "커스텀 범위를 정의한 프로토콜 이름" },
  "context.params.range.tickLower": { label: "하단 Tick (Uniswap V3)", desc: "유동성 범위의 아래쪽 Tick" },
  "context.params.range.tickUpper": { label: "상단 Tick (Uniswap V3)", desc: "유동성 범위의 위쪽 Tick" },
  "context.params.recipient": { label: "수신자의 주소", desc: "결과 토큰을 받는 주소" },
  "context.params.tokenOut.key.address": { label: "출력 토큰의 주소", desc: "단일 토큰 제거 시 받는 토큰의 주소" },
  "context.params.tokenOut.key.chain": { label: "출력 토큰이 있는 네트워크", desc: "출력 토큰이 올라간 네트워크" },
  "context.params.tokenOut.key.hlToken": { label: "출력 토큰 식별자 (하이퍼리퀴드)", desc: "출력 토큰의 하이퍼리퀴드 식별자" },
  "context.params.tokens": { label: "공급 토큰 목록", desc: "풀에 공급할 토큰과 수량 목록" },
  "context.payToken.key.address": { label: "지불 토큰의 주소", desc: "지불에 쓰는 토큰의 컨트랙트 주소" },
  "context.payToken.key.chain": { label: "지불 토큰의 네트워크", desc: "지불 토큰이 있는 네트워크" },
  "context.payToken.key.hlToken": { label: "지불 토큰 식별자 (하이퍼리퀴드)", desc: "지불 토큰의 하이퍼리퀴드 식별자" },
  "context.payloadCount": { label: "실행 항목 수", desc: "제안이 실행할 조치의 개수" },
  "context.payloadTargets": { label: "실행 대상 목록", desc: "제안이 호출할 컨트랙트의 주소 목록" },
  "context.permission": { label: "권한 종류", desc: "부여하거나 회수하는 권한의 종류" },
  "context.permissionLabel": { label: "권한 이름", desc: "프로토콜이 알려준 권한 표시 이름" },
  "context.permissionLimit": { label: "권한 한도", desc: "프로토콜이 정한 권한의 한도값" },
  "context.permittedAmount": { label: "허용 수량 (원본)", desc: "서명이 허용한 수량, 원본 값 (Permit2)" },
  "context.permittedAmountNano": { label: "허용 수량 (비교용)", desc: "크기 비교에 쓰는 허용 수량 (Permit2)" },
  "context.platform.chain": { label: "플랫폼의 네트워크", desc: "런치패드가 있는 네트워크" },
  "context.platform.market": { label: "시장", desc: "대상 시장 (예: BTC-PERP)" },
  "context.platform.name": { label: "플랫폼 이름", desc: "런치패드 이름 (Hyperliquid는 \"hyperliquid\")" },
  "context.platform.version": { label: "플랫폼 버전", desc: "런치패드 버전" },
  "context.pooledEth": { label: "지분에 해당하는 ETH", desc: "지분이 가리키는 stETH의 양 (Lido)" },
  "context.positionId": { label: "포지션 ID", desc: "선물 포지션의 고유 ID" },
  "context.positionState.entryPrice": { label: "진입 가격", desc: "포지션의 진입 가격" },
  "context.positionState.liqPrice": { label: "청산 가격", desc: "포지션의 청산 가격" },
  "context.positionState.markPrice": { label: "마크 가격", desc: "청산을 판단하는 기준 가격" },
  "context.positionState.notionalUsd": { label: "포지션 명목가치 (USD)", desc: "포지션의 달러 명목가치" },
  "context.positionState.sizeBase": { label: "포지션 크기", desc: "기초자산 단위 포지션 크기 (원본)" },
  "context.positionState.unrealizedPnl": { label: "미실현 손익", desc: "아직 실현되지 않은 손익 (+/-)" },
  "context.powerType": { label: "위임할 권한 종류", desc: "투표권·제안권 중 위임 범위" },
  "context.priceImpactBp": { label: "시세 영향도", desc: "이 거래가 시세를 움직이는 정도 (100 = 1%)" },
  "context.proof": { label: "머클 증명", desc: "청구 자격을 증명하는 머클 형제 해시 목록" },
  "context.proposalId": { label: "제안의 번호", desc: "대상 제안의 번호" },
  "context.protocol": { label: "프로토콜 컨트랙트의 주소", desc: "권한을 설정할 대출 프로토콜의 주소 (Aave)" },
  "context.protocolName": { label: "프로토콜 이름", desc: "프로토콜의 종류 이름 (Balancer V2 등)" },
  "context.rateMode": { label: "금리 모드", desc: "변동금리인지 고정금리인지 (Aave)" },
  "context.rateStable": { label: "고정 금리", desc: "고정금리 연이율 (Aave)" },
  "context.rateVariable": { label: "변동 금리", desc: "변동금리 연이율 (Aave)" },
  "context.rawDelegationType": { label: "위임 유형 코드", desc: "체인에 기록되는 위임 유형의 코드" },
  "context.reason": { label: "투표 사유", desc: "투표에 남기는 사유" },
  "context.receiveAToken": { label: "aToken으로 받기", desc: "압류 담보를 aToken으로 받을지 (Aave)" },
  "context.receiveAsTokens": { label: "토큰으로 받기", desc: "참이면 토큰, 거짓이면 지분 재예치" },
  "context.recipient": { label: "수신자", desc: "토큰을 받는 주소" },
  "context.reduceOnly": { label: "감소 전용 여부", desc: "기존 포지션을 줄이기만 하는 주문인지" },
  "context.referral": { label: "추천인의 주소", desc: "스테이킹 추천인의 주소 (Lido)" },
  "context.refundAmount": { label: "환불 수량 (원본)", desc: "환불받는 토큰 양 (원본 형식)" },
  "context.refundAmountNano": { label: "환불 수량 (비교용)", desc: "환불받는 토큰 양 (크기 비교용)" },
  "context.refundAmountUsd": { label: "환불 수량 (USD)", desc: "환불받는 토큰의 달러 가치" },
  "context.refundDue": { label: "환불 예정액", desc: "돌려받을 예정 금액" },
  "context.refundToken.key.address": { label: "환불 토큰의 주소", desc: "환불받는 토큰의 컨트랙트 주소" },
  "context.refundToken.key.chain": { label: "환불 토큰의 네트워크", desc: "환불 토큰이 있는 네트워크" },
  "context.refundToken.key.hlToken": { label: "환불 토큰 식별자 (하이퍼리퀴드)", desc: "환불 토큰의 하이퍼리퀴드 식별자" },
  "context.representative": { label: "대리인의 주소", desc: "새로 등록할 대리인의 주소 (Aave)" },
  "context.representativeChainId": { label: "대리인이 맡을 네트워크", desc: "대리인이 대표할 네트워크의 번호" },
  "context.requestIds": { label: "요청 ID 목록", desc: "출금 요청 NFT의 ID 목록 (Lido)" },
  "context.reserveState.borrowCap": { label: "차입 한도", desc: "시장의 차입 한도 (원본)" },
  "context.reserveState.isFrozen": { label: "시장 동결 여부", desc: "시장이 동결되었는지 여부" },
  "context.reserveState.isPaused": { label: "시장 일시중지 여부", desc: "시장이 일시중지되었는지 여부" },
  "context.reserveState.liquidationBonusBp": { label: "청산 보너스 (bp)", desc: "청산자가 받는 할인폭 (100bp=1%)" },
  "context.reserveState.liquidationThresholdBp": { label: "청산 기준선 (bp)", desc: "청산이 시작되는 담보 비율 (100bp=1%)" },
  "context.reserveState.ltvBp": { label: "담보인정비율 (bp)", desc: "담보로 빌릴 수 있는 비율 (100bp=1%)" },
  "context.reserveState.reserveFactorBp": { label: "예치금 적립률 (bp)", desc: "이자 중 적립되는 비율 (100bp=1%)" },
  "context.reserveState.supplyCap": { label: "예치 한도", desc: "시장의 예치 한도 (원본)" },
  "context.reserveState.totalBorrow": { label: "총 차입액", desc: "시장의 전체 차입액 (원본)" },
  "context.reserveState.totalSupply": { label: "총 예치액", desc: "시장의 전체 예치액 (원본)" },
  "context.reserveState.utilizationBp": { label: "자금 사용률 (bp)", desc: "예치금 중 빌려간 비율 (100bp=1%)" },
  "context.rewardToken.key.address": { label: "보상 토큰의 주소", desc: "보상 토큰의 컨트랙트 주소 (ERC20)" },
  "context.rewardToken.key.chain": { label: "보상 토큰이 있는 네트워크", desc: "보상 토큰이 배포된 네트워크" },
  "context.rewardToken.key.hlToken": { label: "보상 토큰 식별자 (하이퍼리퀴드)", desc: "보상 토큰의 하이퍼리퀴드 식별자" },
  "context.routeEstimatedOut": { label: "경로 예상 수령량 (원본)", desc: "전체 경로의 예상 출력량 합계" },
  "context.saleId": { label: "판매 ID", desc: "런치패드 판매의 식별자" },
  "context.saleState.hardCap": { label: "판매 상한 (하드캡)", desc: "모집 가능한 최대 금액" },
  "context.saleState.isActive": { label: "판매 진행중 여부", desc: "판매가 진행 중인가" },
  "context.saleState.saleWindowEnd": { label: "판매 마감 시각", desc: "판매가 끝나는 시각" },
  "context.saleState.saleWindowStart": { label: "판매 시작 시각", desc: "판매가 시작되는 시각" },
  "context.saleState.softCap": { label: "판매 하한 (소프트캡)", desc: "판매 성립 최소 금액" },
  "context.saleState.totalCommitted": { label: "총 모집액", desc: "지금까지 모인 총 금액" },
  "context.saleState.vestSchedule.cliff": { label: "베스팅 클리프 시각", desc: "이 시각 전에는 해제 없음 (클리프)" },
  "context.saleState.vestSchedule.curve.description": { label: "베스팅 곡선 설명", desc: "커스텀 해제 방식 설명" },
  "context.saleState.vestSchedule.curve.kind": { label: "베스팅 곡선 종류", desc: "해제 방식 (linear/stepped/custom)" },
  "context.saleState.vestSchedule.curve.steppedPointAmounts": { label: "구간별 베스팅 수량", desc: "각 구간에서 풀리는 토큰 양 목록" },
  "context.saleState.vestSchedule.curve.steppedPointTimes": { label: "구간별 베스팅 시각", desc: "각 구간이 풀리는 시각 목록" },
  "context.saleState.vestSchedule.end": { label: "베스팅 종료 시각", desc: "해제가 끝나는 시각" },
  "context.saleState.vestSchedule.start": { label: "베스팅 시작 시각", desc: "해제가 시작되는 시각" },
  "context.saleState.vestSchedule.total": { label: "베스팅 총량", desc: "베스팅으로 풀릴 토큰 총량" },
  "context.scope": { label: "취소 범위", desc: "특정 주문만 또는 전체 취소" },
  "context.scope.chain": { label: "권한의 네트워크", desc: "권한 범위가 적용되는 네트워크" },
  "context.scope.contract": { label: "컨트랙트의 주소", desc: "권한 대상 컨트랙트의 주소" },
  "context.scope.kind": { label: "권한 종류", desc: "해제할 권한의 종류 (erc20/nft 등)" },
  "context.scope.mask": { label: "권한 비트마스크", desc: "무효화할 논스를 표시한 비트마스크 (Permit2)" },
  "context.scope.nftKey.address": { label: "NFT 컨트랙트의 주소", desc: "NFT 컬렉션 컨트랙트의 주소" },
  "context.scope.nftKey.chain": { label: "NFT의 네트워크", desc: "NFT가 있는 네트워크" },
  "context.scope.nftKey.contract": { label: "NFT 컬렉션의 주소", desc: "NFT 컬렉션 컨트랙트의 주소" },
  "context.scope.nftKey.hlToken": { label: "NFT 식별자 (하이퍼리퀴드)", desc: "NFT의 하이퍼리퀴드 식별자" },
  "context.scope.nftKey.standard": { label: "NFT 규격 (ERC)", desc: "NFT 규격 (erc721/erc1155)" },
  "context.scope.nftKey.tokenId": { label: "NFT의 번호", desc: "NFT 토큰의 번호 (16진수)" },
  "context.scope.spender": { label: "지출 승인 대상", desc: "내 토큰을 가져갈 권한을 받는 컨트랙트" },
  "context.scope.token.key.address": { label: "권한 범위 토큰의 주소", desc: "권한 대상 토큰 컨트랙트의 주소" },
  "context.scope.token.key.chain": { label: "권한 범위 토큰의 네트워크", desc: "권한 대상 토큰이 있는 네트워크" },
  "context.scope.token.key.hlToken": { label: "권한 대상 토큰 식별자 (하이퍼리퀴드)", desc: "권한 대상 토큰의 하이퍼리퀴드 식별자" },
  "context.scope.wordPos": { label: "권한 워드 위치", desc: "논스가 저장된 워드 위치 (Permit2)" },
  "context.sell.key.address": { label: "팔 토큰의 주소", desc: "매도할 토큰 컨트랙트의 주소" },
  "context.sell.key.chain": { label: "팔 토큰이 있는 네트워크", desc: "매도할 토큰이 올라간 네트워크" },
  "context.sell.key.hlToken": { label: "팔 토큰 식별자 (하이퍼리퀴드)", desc: "파는 토큰의 하이퍼리퀴드 식별자" },
  "context.sellAmount": { label: "매도 수량 (원본)", desc: "주문에서 팔려는 토큰의 양" },
  "context.sellAmountNano": { label: "매도 수량 (비교용)", desc: "크기 비교에 쓰는 매도 수량" },
  "context.sellAmountUsd": { label: "매도 수량 (USD)", desc: "매도 수량의 달러 환산값" },
  "context.shares": { label: "지분", desc: "프로토콜 내부의 지분 단위 (Lido)" },
  "context.side": { label: "스왑 방향", desc: "자산을 사는지 파는지 (Aave GHO)" },
  "context.sig": { label: "서명값", desc: "서명 방식 청구에 쓰는 서명 (EIP-712)" },
  "context.sigDeadline": { label: "서명 마감 시각", desc: "서명이 만료되는 시각, 유닉스 초" },
  "context.signature": { label: "주문 서명값", desc: "주문에 대한 16진수 서명값 (EIP-712)" },
  "context.signed": { label: "사전 서명 여부", desc: "주문을 사전 서명으로 등록하는지 여부 (CoW Swap)" },
  "context.size.amount": { label: "주문 수량 (원본)", desc: "토큰 단위 그대로의 주문 수량 (16진수)" },
  "context.size.amountDecimal": { label: "주문 수량 (소수)", desc: "기초자산 단위 소수 수량 (하이퍼리퀴드)" },
  "context.size.amountUsd": { label: "주문 수량 (USD)", desc: "주문의 달러 환산 수량" },
  "context.size.amountUsdNano": { label: "주문 수량 (USD, 비교용)", desc: "크기 비교에 쓰는 달러 수량" },
  "context.size.collateral": { label: "주문 담보", desc: "주문에 거는 담보 양 (원본)" },
  "context.size.kind": { label: "주문 크기 종류", desc: "주문 크기를 지정하는 방식" },
  "context.size.leverage": { label: "주문 레버리지 (원본)", desc: "담보 기준으로 정한 주문의 배율" },
  "context.slippageBp": { label: "슬리피지 허용치", desc: "체결가가 예상가에서 벗어나도 되는 한도 (100 = 1%)" },
  "context.source.chain": { label: "출처 프로토콜이 있는 네트워크", desc: "에어드랍을 배포한 프로토콜의 네트워크" },
  "context.source.market": { label: "출처 세부 시장", desc: "프로토콜 안의 세부 시장 (예: Morpho Blue)" },
  "context.source.name": { label: "출처 프로토콜 이름", desc: "에어드랍을 배포한 프로토콜 (하이퍼리퀴드는 \"hyperliquid\")" },
  "context.source.version": { label: "출처 프로토콜 버전", desc: "배포 프로토콜의 버전 (예: v2)" },
  "context.sourceDex": { label: "출발 DEX 이름", desc: "자산이 출발하는 DEX의 이름 (하이퍼리퀴드)" },
  "context.spender": { label: "지출 승인 대상", desc: "내 토큰을 가져갈 권한을 받는 컨트랙트" },
  "context.staker": { label: "스테이커의 주소", desc: "예치를 대신 맡길 스테이커 (EigenLayer)" },
  "context.startTime": { label: "시작 시각", desc: "주문이 유효해지는 시각" },
  "context.strategies": { label: "전략 컨트랙트 목록", desc: "지분을 출금할 전략 컨트랙트들 (EigenLayer)" },
  "context.strategy": { label: "전략 컨트랙트의 주소", desc: "예치를 받는 전략 컨트랙트 (EigenLayer)" },
  "context.supplyApy": { label: "예치 연이율 (APY)", desc: "예치 시 받는 연이율" },
  "context.support": { label: "찬성 여부", desc: "제안에 찬성하면 참" },
  "context.swapper": { label: "주문자의 주소", desc: "정산 대상 주문을 낸 사람의 주소" },
  "context.target": { label: "대상 컨트랙트의 주소", desc: "호출하는 대상 컨트랙트의 주소" },
  "context.token": { label: "토큰 이름", desc: "보내는 토큰의 이름 (하이퍼리퀴드)" },
  "context.token.key.address": { label: "토큰의 주소", desc: "ERC20 토큰 컨트랙트의 주소" },
  "context.token.key.chain": { label: "토큰의 네트워크", desc: "토큰이 있는 네트워크" },
  "context.token.key.hlToken": { label: "토큰 식별자 (하이퍼리퀴드)", desc: "토큰의 하이퍼리퀴드 식별자" },
  "context.tokenIn.key.address": { label: "입력 토큰의 주소", desc: "입력 토큰 컨트랙트의 주소" },
  "context.tokenIn.key.chain": { label: "입력 토큰이 있는 네트워크", desc: "입력 토큰이 올라간 네트워크" },
  "context.tokenIn.key.hlToken": { label: "입력 토큰 식별자 (하이퍼리퀴드)", desc: "입력 토큰의 하이퍼리퀴드 식별자" },
  "context.tokenOut.key.address": { label: "출력 토큰의 주소", desc: "출력 토큰 컨트랙트의 주소" },
  "context.tokenOut.key.chain": { label: "출력 토큰이 있는 네트워크", desc: "출력 토큰이 올라간 네트워크" },
  "context.tokenOut.key.hlToken": { label: "출력 토큰 식별자 (하이퍼리퀴드)", desc: "출력 토큰의 하이퍼리퀴드 식별자" },
  "context.unlockTime": { label: "락 해제 시각", desc: "락이 풀리는 시각 (유닉스 초)" },
  "context.unrealizedPnlNow": { label: "현재 미실현 손익", desc: "지금 시점의 미실현 손익 (+/-)" },
  "context.useATokens": { label: "aToken으로 상환", desc: "예치 증서 aToken으로 갚을지 (Aave)" },
  "context.user": { label: "사용자의 주소", desc: "작업을 수행하는 사용자의 주소" },
  "context.userAccountState.freeMarginUsd": { label: "여유 증거금 (USD)", desc: "새 주문에 쓸 수 있는 증거금" },
  "context.userAccountState.openPositions": { label: "열린 포지션 목록", desc: "현재 열려 있는 포지션 목록" },
  "context.userAccountState.totalCollateralUsd": { label: "총 담보 (USD)", desc: "계정의 전체 담보 가치" },
  "context.userAccountState.usedMarginUsd": { label: "사용 중 증거금 (USD)", desc: "이미 묶여 있는 증거금" },
  "context.userCap": { label: "1인 한도", desc: "한 사람이 모집할 수 있는 최대 금액" },
  "context.userCommitted": { label: "내 모집액", desc: "내가 지금까지 넣은 금액" },
  "context.userStateBefore.availableBorrowUsd": { label: "거래 전 차입 가능액 (USD)", desc: "거래 전 더 빌릴 수 있는 금액 (USD)" },
  "context.userStateBefore.healthFactor": { label: "거래 전 건전성 지수", desc: "거래 전 청산 위험도 지수" },
  "context.userStateBefore.totalCollatUsd": { label: "거래 전 총 담보 (USD)", desc: "거래 전 담보의 총가치 (USD)" },
  "context.userStateBefore.totalDebtUsd": { label: "거래 전 총 빚 (USD)", desc: "거래 전 빚의 총액 (USD)" },
  "context.usesConduit": { label: "컨듀잇 사용 여부", desc: "컨듀잇 경유로 전송하는지 (Seaport)" },
  "context.validUntil": { label: "유효 마감 시각", desc: "주문이 유효한 마감 시각 (Unix)" },
  "context.validator": { label: "검증인의 주소", desc: "위임 대상 검증인의 주소 (하이퍼리퀴드)" },
  "context.value": { label: "함께 보내는 코인 금액", desc: "호출과 함께 보내는 코인(ETH) 금액" },
  "context.venue.adapter": { label: "어댑터 컨트랙트의 주소", desc: "프로토콜에 연결하는 어댑터의 주소 (Aave V3)" },
  "context.venue.baseAsset.key.address": { label: "기준 자산의 주소", desc: "시장의 기준 자산 토큰의 주소 (Compound V3)" },
  "context.venue.baseAsset.key.chain": { label: "기준 자산의 네트워크", desc: "기준 자산이 있는 네트워크" },
  "context.venue.baseAsset.key.hlToken": { label: "기준 자산 식별자 (하이퍼리퀴드)", desc: "프로토콜 기준 자산의 하이퍼리퀴드 식별자" },
  "context.venue.binStep": { label: "Bin 간격 (Trader Joe LB)", desc: "유동성 Bin 사이의 간격, bp 단위" },
  "context.venue.chain": { label: "프로토콜이 있는 네트워크", desc: "프로토콜이 올라간 블록체인 네트워크" },
  "context.venue.comet": { label: "Comet 시장 컨트랙트의 주소", desc: "대출 시장 컨트랙트의 주소 (Compound V3)" },
  "context.venue.comptroller": { label: "컴프트롤러 컨트랙트의 주소", desc: "시장 전체를 관리하는 컨트랙트의 주소 (Compound V2)" },
  "context.venue.contract": { label: "프로토콜 컨트랙트의 주소", desc: "주문을 처리하는 컨트랙트의 주소" },
  "context.venue.controller": { label: "게이지 컨트롤러의 주소", desc: "게이지 투표 가중치를 배분하는 컨트랙트 (Curve)" },
  "context.venue.distributor": { label: "수수료 분배 컨트랙트의 주소", desc: "락 참여자에게 수수료를 나눠주는 컨트랙트 (Curve)" },
  "context.venue.escrow": { label: "투표 락 컨트랙트의 주소", desc: "CRV를 락해 투표권을 만드는 컨트랙트 (Curve)" },
  "context.venue.executor": { label: "실행 컨트랙트의 주소", desc: "스왑을 실제로 실행하는 컨트랙트 (1inch)" },
  "context.venue.factory": { label: "팩토리의 주소", desc: "풀을 만들어내는 팩토리의 주소 (Uniswap V2)" },
  "context.venue.feeTierBp": { label: "수수료 등급 (Uniswap V3)", desc: "풀의 수수료율, bp 단위" },
  "context.venue.gauge": { label: "게이지 컨트랙트의 주소", desc: "LP를 예치하는 보상 게이지 (Curve)" },
  "context.venue.governance": { label: "거버넌스 컨트랙트의 주소", desc: "제안을 관리하는 컨트랙트의 주소 (Aave)" },
  "context.venue.gsm": { label: "GHO 발행·상환 모듈의 주소", desc: "GHO를 찍거나 갚는 컨트랙트 (Aave)" },
  "context.venue.hooks": { label: "훅 컨트랙트의 주소 (Uniswap V4)", desc: "풀에 끼워 넣은 훅 컨트랙트의 주소" },
  "context.venue.isMeta": { label: "메타풀 여부", desc: "메타풀인지 여부 (Curve)" },
  "context.venue.marketId": { label: "마켓의 번호", desc: "시장을 가리키는 번호 (Aave V3)" },
  "context.venue.marketIdStr": { label: "마켓의 식별자", desc: "시장을 가리키는 32바이트 식별자 (Morpho Blue)" },
  "context.venue.minter": { label: "발행 컨트랙트의 주소", desc: "쌓인 CRV 보상을 발행하는 컨트랙트 (Curve)" },
  "context.venue.module": { label: "세이프티 모듈의 주소", desc: "토큰을 스테이킹하는 안전 모듈 (Aave)" },
  "context.venue.nCoins": { label: "풀 코인 수 (Curve)", desc: "풀에 담긴 토큰 종류의 수" },
  "context.venue.name": { label: "프로토콜의 이름", desc: "스왑·풀 프로토콜의 식별 이름 (Uniswap V3 등)" },
  "context.venue.pair": { label: "페어 컨트랙트의 주소 (Trader Joe LB)", desc: "토큰 쌍 거래 컨트랙트의 주소" },
  "context.venue.pool": { label: "풀의 주소", desc: "거래가 일어나는 풀의 주소" },
  "context.venue.poolId": { label: "풀 ID", desc: "풀의 식별자 (Balancer·Uniswap V4)" },
  "context.venue.poolManager": { label: "풀 매니저의 주소 (Uniswap V4)", desc: "모든 풀을 관리하는 컨트랙트의 주소" },
  "context.venue.poolType": { label: "풀 종류 (Balancer)", desc: "풀의 유형 (예: weighted)" },
  "context.venue.reactor": { label: "리액터 컨트랙트의 주소 (UniswapX)", desc: "주문을 정산하는 리액터의 주소" },
  "context.venue.routeHash": { label: "경로 해시", desc: "스왑 경로를 요약한 해시값 (1inch)" },
  "context.venue.router": { label: "라우터의 주소", desc: "스왑을 중계하는 라우터의 주소 (1inch)" },
  "context.venue.settlement": { label: "정산 컨트랙트의 주소 (CoW Swap)", desc: "거래를 정산하는 컨트랙트의 주소" },
  "context.venue.stakeToken": { label: "스테이킹 토큰 컨트랙트의 주소", desc: "예치 대상이 되는 엄브렐라 금고 (Aave)" },
  "context.venue.token.key.address": { label: "투표권 토큰의 주소", desc: "투표권을 가진 토큰 컨트랙트의 주소" },
  "context.venue.token.key.chain": { label: "투표권 토큰의 네트워크", desc: "투표권 토큰이 있는 네트워크" },
  "context.venue.token.key.hlToken": { label: "투표권 토큰 식별자 (하이퍼리퀴드)", desc: "투표권 토큰의 하이퍼리퀴드 식별자" },
  "context.venue.vault": { label: "볼트의 주소 (Balancer V2)", desc: "스왑 자금을 모아두는 Vault의 주소" },
  "context.venue.verifyingContract": { label: "서명 검증 컨트랙트의 주소 (EIP-712)", desc: "주문 서명을 확인하는 컨트랙트 (1inch)" },
  "context.venue.votingMachine": { label: "투표 집계 컨트랙트의 주소", desc: "표를 집계하는 컨트랙트의 주소 (Aave)" },
  "context.victim": { label: "청산 대상의 주소", desc: "청산되는 대상의 주소" },
  "context.victimState.availableBorrowUsd": { label: "대상의 차입 가능액 (USD)", desc: "청산 대상이 더 빌릴 수 있는 금액 (USD)" },
  "context.victimState.healthFactor": { label: "대상의 건전성 지수", desc: "청산 대상의 청산 위험도 지수" },
  "context.victimState.totalCollatUsd": { label: "대상의 총 담보 (USD)", desc: "청산 대상 담보의 총가치 (USD)" },
  "context.victimState.totalDebtUsd": { label: "대상의 총 빚 (USD)", desc: "청산 대상 빚의 총액 (USD)" },
  "context.votingPower": { label: "위임 투표권", desc: "위임되는 투표권의 양 (원본)" },
  "context.wei": { label: "위임 수량 (wei)", desc: "위임하거나 해제하는 토큰의 양 (wei)" },
  "context.weightBp": { label: "투표 가중치 (bp)", desc: "게이지에 줄 가중치 (0~10000bp)" },
  "context.withdrawable": { label: "출금 가능액", desc: "지금 뺄 수 있는 모집액" },
  "context.withdrawer": { label: "출금자의 주소", desc: "출금을 마치고 자금을 받을 주소" },
  "context.witnessType": { label: "서명 witness 타입", desc: "서명에 함께 담는 추가 데이터 타입 (Permit2 Witness)" },
  "context.zone": { label: "검증 존의 주소", desc: "제한 주문을 검증하는 존 (Seaport)" },
};
