/**
 * Protocol resolver registry — `<protocol>:<scope>` → resolver function.
 *
 * Each protocol file (e.g. `aave_v3.ts`) exports its resolver(s) and is
 * imported here to register entries in `PROTOCOL_SOURCE_RESOLVERS`.
 *
 * Add a new protocol:
 *  1. Implement resolver(s) under `scripts/resolvers/<protocol>.ts`.
 *  2. Register resolver(s) in `PROTOCOL_SOURCE_RESOLVERS` below.
 *  3. Document the source kind in `registryV2/docs/SOURCE_CATALOG.md`.
 *
 * `build-index.ts` validates protocol-aware source kinds from this registry;
 * there is no separate source-kind union to keep in sync.
 */

import {
  atokensResolver,
  variableDebtsResolver,
  stableDebtsResolver,
} from "./aave_v3.ts";
import {
  factoryCrvusdResolver,
  factoryCryptoBaseResolver,
  factoryCryptoResolver,
  factoryTricryptoBaseResolver,
  factoryTricryptoResolver,
  factoryTwocryptoBaseResolver,
  factoryTwocryptoResolver,
  factoryV2Resolvers,
  gaugesResolver,
  stableNgResolvers,
} from "./curve.ts";
import type { ProtocolResolver, ProtocolSourceKind } from "./types.ts";

export { rpcClient } from "./rpc.ts";
export type {
  ProtocolResolver,
  ProtocolResolvedAddress,
  ProtocolSourceKind,
  ResolverOpts,
  Hex,
  CacheEntry,
  RpcClient,
} from "./types.ts";

/** Map from source kind → resolver. Curve StableSwap-NG entries are generated by coin count. */
const protocolSourceResolverList: ProtocolResolver[] = [
  atokensResolver,
  variableDebtsResolver,
  stableDebtsResolver,
  gaugesResolver,
  factoryCrvusdResolver,
  factoryCryptoBaseResolver,
  factoryCryptoResolver,
  factoryTricryptoBaseResolver,
  factoryTricryptoResolver,
  factoryTwocryptoBaseResolver,
  factoryTwocryptoResolver,
  ...factoryV2Resolvers,
  ...stableNgResolvers,
];

export const PROTOCOL_SOURCE_RESOLVERS: Record<ProtocolSourceKind, ProtocolResolver> =
  Object.fromEntries(protocolSourceResolverList.map((resolver) => [resolver.source, resolver]));
